[Theme]
Current=sugar-candy

[General]
DisplayServer=x11

[Theme-Settings]
Background=/usr/share/backgrounds/background.jpg
BlurRadius=32
ForceHideCompletePassword=false
HeaderText=Welcome
AccentColor=#89b4fa
FormPosition=center
FullBlur=true
PartialBlur=false
